"""ZDT Y42 dual-firmware (X/Emm) closed-loop stepper driver."""

from .commands.base import CommandError, FirmwareCapabilityError
from .configs import (
    Address,
    ChecksumMode,
    ControlMode,
    Direction,
    FirmwareType,
    HomingMode,
    LockParamLevel,
    MotionMode,
    MotorType,
    StoreFlag,
    SyncFlag,
)
from .device import Y42Device
from .parameters import (
    DMX512Params,
    DeviceParams,
    EmmAutoRunParams,
    EmmConfigParams,
    EmmJogParams,
    EmmPIDParams,
    EmmPositionParams,
    EmmSystemStatusParams,
    HomeMotorStatus,
    HomingParams,
    HomingStatus,
    IOStatus,
    MotorRHParams,
    MotorStatus,
    OptionStatus,
    ProtectionThreshold,
    VersionParams,
    XAutoRunParams,
    XConfigParams,
    XJogCurrentLimitParams,
    XJogParams,
    XPIDParams,
    XPositionDirectLimitedParams,
    XPositionDirectParams,
    XPositionTrapLimitedParams,
    XPositionTrapParams,
    XSystemStatusParams,
    XTorqueLimitedParams,
    XTorqueParams,
)

__version__ = "0.1.0"

__all__ = [
    # device
    "Y42Device",
    "__version__",
    # errors
    "CommandError",
    "FirmwareCapabilityError",
    # configs / enums
    "Address",
    "ChecksumMode",
    "ControlMode",
    "Direction",
    "FirmwareType",
    "HomingMode",
    "LockParamLevel",
    "MotionMode",
    "MotorType",
    "StoreFlag",
    "SyncFlag",
    # parameters
    "DeviceParams",
    "EmmJogParams",
    "EmmPositionParams",
    "XJogParams",
    "XJogCurrentLimitParams",
    "XTorqueParams",
    "XTorqueLimitedParams",
    "XPositionDirectParams",
    "XPositionDirectLimitedParams",
    "XPositionTrapParams",
    "XPositionTrapLimitedParams",
    "HomingParams",
    "HomingStatus",
    "VersionParams",
    "MotorRHParams",
    "EmmPIDParams",
    "XPIDParams",
    "MotorStatus",
    "IOStatus",
    "HomeMotorStatus",
    "OptionStatus",
    "ProtectionThreshold",
    "DMX512Params",
    "EmmSystemStatusParams",
    "XSystemStatusParams",
    "EmmConfigParams",
    "XConfigParams",
    "EmmAutoRunParams",
    "XAutoRunParams",
]
